# Generated by Django 4.2.1 on 2023-07-15 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MangaCollection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=40)),
                ('bought', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='manga-collection-imgs/')),
                ('status', models.IntegerField(choices=[(0, 'Buying'), (1, 'Finished'), (2, 'Wish')], default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
