# Generated by Django 4.2.1 on 2023-07-12 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mangas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manga',
            old_name='user',
            new_name='owner',
        ),
    ]
