# Generated by Django 4.2.1 on 2023-07-12 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangas', '0003_alter_manga_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='manga-imgs/'),
        ),
    ]
