# Generated by Django 4.2.1 on 2023-07-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangas', '0004_manga_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
