# Generated by Django 4.2.1 on 2023-07-13 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangas', '0006_manga_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='notes',
            field=models.TextField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='manga',
            name='url',
            field=models.URLField(blank=True, default=None, help_text='Works better with Mangalivre website.', null=True),
        ),
    ]
