# Generated by Django 4.2.1 on 2023-07-13 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangas', '0007_manga_notes_alter_manga_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manga',
            name='is_finished',
        ),
        migrations.AddField(
            model_name='manga',
            name='status',
            field=models.IntegerField(choices=[(0, 'Ongoing'), (1, 'Finished'), (2, 'Wish to read'), (3, 'Dropped')], default=0),
        ),
    ]
